### ISSUE TITLE
How to install pre-compiled v8?

### ISSUE THREAD

**Issue by caracal7** [uuhan/rvb#1]
How to install pre-compiled v8 for OSX / Debian?

Cant find successful information about it

**Comment by uuhan** [comment]
> How to install pre-compiled v8 for OSX / Debian?
> 
> Cant find successful information about it

hi, @caracal7

The best way is to follow the building guide of v8 [wiki](https://v8.dev/docs/build).

I find that there is a v8 package in homebrew of version 7.4, but I have not tested that version.

I will try to make that version compatible.

**Comment by uuhan** [comment]
#2 
This changeset make master branch compatible with Homebrew version of v8(currently 7.4.288.25)
